---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Configure the Menu Bar

- name: (Menu Bar) Set the Menu Bar
  osx_defaults:
    domain: com.apple.systemuiserver
    type: array
    key: menuExtras
    value:
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/User.menu"
      - "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"
      - "/System/Library/CoreServices/Menu Extras/Displays.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
  notify: restart MenuBar

- name: (Menu Bar) Show Siri
  osx_defaults:
    domain: com.apple.systemuiserver
    type: int
    state: present
    key: "NSStatusItem Visible Siri"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show Time Machine
  osx_defaults:
    domain: com.apple.systemuiserver
    type: int
    state: present
    key: "NSStatusItem Visible com.apple.menuextra.TimeMachine"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show AirPlay
  osx_defaults:
    domain: com.apple.systemuiserver
    type: int
    state: present
    key: "NSStatusItem Visible com.apple.menuextra.airplay"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show WiFi
  osx_defaults:
    domain: com.apple.controlcenter
    type: int
    state: present
    key: "NSStatusItem Visible WiFi"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show Screen Mirroring Always
  osx_defaults:
    domain: com.apple.controlcenter
    type: string
    state: present
    key: "NSStatusItem Visible ScreenMirroring"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show Bluetooth
  osx_defaults:
    domain: com.apple.controlcenter
    type: int
    state: present
    key: "NSStatusItem Visible Bluetooth"
    value: 1
  notify: restart MenuBar

- name: (Menu Bar) Show Clock
  osx_defaults:
    domain: com.apple.systemuiserver
    type: int
    state: present
    key: "NSStatusItem Visible com.apple.menuextra.clock"
    value: 1
  notify: restart MenuBar
