---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Deploy common directories I use in my home directory and throughout the system.

- name: (Profile) Deploy Code directory
  file:
    path: "~/Code"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: (Profile) Deploy Protected directory
  file:
    path: "~/Protected"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: (Profile) Deploy Scratch directory
  file:
    path: "~/Scratch"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700
