---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Install Rosetta 2 on Apple Silicon machines

- name: (Rosetta) Install Rosetta 2
  become: yes
  become_user: root
  command:
    cmd: 'softwareupdate --install-rosetta --agree-to-license'
    creates: "/Library/Apple/System/Library/Receipts/com.apple.pkg.RosettaUpdateAuto.plist"
