---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Configure virtual environments for development

- name: (Virtual Environments) Install Ruby 2.7.0
  shell: >
    RUBY_CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.7.0
  args:
    executable: '/bin/zsh'
    creates: "~/.rbenv/versions/2.7.0"

- name: (Virtual Environments) Set Ruby 2.7.0 as the global environment
  shell: >
    rbenv global 2.7.0
  args:
    executable: '/bin/zsh'
    creates: "~/.rbenv/version"

- name: (Virtual Environments) Install Python 3.9.0
  shell: >
    /opt/homebrew/bin/pyenv install --patch 3.9.0
  args:
    executable: '/bin/zsh'
    creates: "~/.pyenv/versions/3.9.0"

- name: (Virtual Environments) Set Python 3.8.0 as the global environment
  command:
    cmd: 'pyenv global 3.8.0'
    creates: "~/.pyenv/version"
