---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Configure virtual environments for development

- name: (Virtual Environments) Install Ruby 3.3.0
  shell: >
    rbenv install 3.3.0
  args:
    executable: '/bin/zsh'
    creates: "~/.rbenv/versions/3.3.0"
  ignore_errors: true

- name: (Virtual Environments) Set Ruby 3.3.0 as the global environment
  shell: >
    rbenv global 3.3.0
  args:
    executable: '/bin/zsh'
    creates: "~/.rbenv/version"
  ignore_errors: true
