---
#
# Project:: Ansible Role - Mac Setup
#
# Copyright 2020, Matthew Ahrenstein, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: @ahrenstein
#
# See LICENSE
#

# Configure virtual environments for development

- name: (Virtual Environments) Install Ruby 2.7.0
  shell: >
    RUBY_CFLAGS="-Wno-error=implicit-function-declaration" arch -x86_64 /opt/homebrew/bin/rbenv install 2.7.0
  args:
    executable: '/bin/zsh'
    creates: "~/.rbenv/versions/2.7.0"

- name: (Virtual Environments) Set Ruby 2.7.0 as the global environment
  command:
    cmd: 'rbenv global 2.7.0'
    creates: "~/.rbenv/version"

- name: (Virtual Environments) Install Python 3.8.0
  shell: >
    CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun
    --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib
    -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.8.0
    < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
  environment:
    LDFLAGS: "-L/usr/local/opt/zlib/lib"
    CPPFLAGS: "-I/usr/local/opt/zlib/include"
  args:
    executable: '/bin/zsh'
    creates: "~/.pyenv/versions/3.8.0"

- name: (Virtual Environments) Set Python 3.8.0 as the global environment
  command:
    cmd: 'pyenv global 3.8.0'
    creates: "~/.pyenv/version"
